---
  - name: This module only works on CentOS 6 x86
    assert:
      that:
        - "ansible_userspace_bits == '32'"
        - "ansible_os_family == 'RedHat'"
# FIXME: check why it does not work
#        - "ansible_lsb['major_release'] == '6'"

  - name: Install compat–gcc-34-c++
    yum: name=compat-gcc-34-c++ state=installed

  - name: Install libstdc++
    yum: name=libstdc++ state=installed

  - name: Install KSH
    yum: name=ksh state=installed

  - name: Install xauth (needed by smconsole)
    yum: name=xorg-x11-xauth state=installed

  - name: Install libXrender (needed by smconsole)
    yum: name=libXrender state=installed

  - name: Install libXtst (needed by smconsole)
    yum: name=libXtst state=installed

  - name: Install RNGD
    yum: name=rng-tools state=installed

  - name: Install the RNGD configuration
    lineinfile: dest=/etc/sysconfig/rngd line='EXTRAOPTIONS="-r /dev/urandom -o /dev/random -b -t .1"' regexp="^EXTRAOPTIONS="

  - name: Restart RNGD and make sure it is enabled
    service: name=rngd state=restarted enabled=yes

  - name: Install patch (needed by ansible)
    yum: name=patch state=installed
