---

  - name: This module only works on CentOS 6 x86
    assert:
      that:
        - "ansible_os_family == 'RedHat'"

  - name: Set the iptables rules
    template: dest=/etc/sysconfig/iptables src=iptables-rules
    tags: iptables

  - name: Make sure iptables is enabled
    service: name=iptables state=restarted enabled=yes
    tags: iptables
    
