---

 - name: Bootstrap one or more RHEL7 nodes
   hosts: bootstrap
   become: no
   roles:
    - bootstrap
    - register-rhn

 - name: Install the required package for an OpenShift Lab
   hosts: lab
   become: yes
   vars:
    - basedir: "{{ lookup('env', 'BASEDIR') }}"
   roles:
    - { role: base }
    - { role: openshift-prereq }
    - { role: name-resolution }
    - { role: docker, when: "'admin' not in group_names" }
    - { role: nfs, when: "'admin' in group_names" }
    - { role: openshift-install, when: "'admin' in group_names" }
    - { role: openshift-postinstall, when: "'masters' in group_names" }
