---

 - name: Bootstrap a CentOS node
   hosts: bootstrap
   sudo: no
   roles:
    - bootstrap

 - name: CA SiteMinder Demo
   hosts: sm
   sudo: yes
   roles:
     - bootstrap
     - base
     - vmware-tools
     - java-7
     - ca-directory
     - siteminder-common
     - siteminder-policy-server
     - siteminder-adminui
     - apache-2.2
     - tomcat-7
     - siteminder-webagent
     - prepare-to-export
     - service-control
